spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:KzHistory}?currentSchema=${DEFAULT_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
        default_schema: ${DEFAULT_SCHEMA:public}
    hibernate:
      ddl-auto: create-drop
    show-sql: ${JPA_SHOW_SQL:false}
file:
  upload-dir: ./static
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8080

